= Downloads
:dist: https://www.apache.org/dist/felix
:mirror: https://www.apache.org/dyn/closer.lua/felix
:query: ?action=download
:repo-base: https://github.com/apache

Use the https://downloads.apache.org/felix/KEYS[KEYS] file contents to https://www.apache.org/info/verification.html[validate] the artifacts.

If available, the version links to the subproject changelog.

== Felix Framework Distribution

[cols="5*",opts="headers"]
|===
//|Sub project
|Module
|Version
|Binary
|tar.gz Source
|zip Source

|===

jsonpathTable2::example$downloads.yml['$.framework.*', 'title|!!changelog ? `{repo-base}/$\{changelog}[$\{version}]` : version|`{mirror}/$\{artifactId}-$\{version}.zip{query}[zip] ({dist}/$\{artifactId}-$\{version}.jar.asc[asc], {dist}/$\{artifactId}-$\{version}.jar.sha1[sha1])` |!!targz ?  `{mirror}/$\{artifactId}-$\{version}-source-release.tar.gz{query}[tar.gz] ({dist}/$\{artifactId}-$\{version}-source-release.tar.gz.asc[asc], {dist}/$\{artifactId}-$\{version}-source-release.tar.gz.sha1[sha1])` : "" |`{mirror}/$\{artifactId}-$\{version}-source-release.zip{query}[zip] ({dist}/$\{artifactId}-$\{version}-source-release.zip.asc[asc], {dist}/$\{artifactId}-$\{version}-source-release.zip.sha1[sha1])`']

== Subprojects

[cols="5*",opts="headers"]
|===
//|Sub project
|Module
|Version
|Binary
|tar.gz Source
|zip Source

|===

jsonpathTable2::example$downloads.yml['$.subprojects.*', 'title|!!changelog ? `{repo-base}/$\{changelog}[$\{version}]` : version|!!jar ? `{mirror}/$\{artifactId}-$\{version}.jar{query}[jar] ({dist}/$\{artifactId}-$\{version}.jar.asc[asc], {dist}/$\{artifactId}-$\{version}.jar.sha1[sha1])` : "" |!!targz ?  `{mirror}/$\{artifactId}-$\{version}-$\{source_classifier}.tar.gz{query}[tar.gz] ({dist}/$\{artifactId}-$\{version}-$\{source_classifier}.tar.gz.asc[asc], {dist}/$\{artifactId}-$\{version}-$\{source_classifier}.tar.gz.sha1[sha1])` : "" |`{mirror}/$\{artifactId}-$\{version}-$\{source_classifier}.zip{query}[zip] ({dist}/$\{artifactId}-$\{version}-$\{source_classifier}.zip.asc[asc], {dist}/$\{artifactId}-$\{version}-$\{source_classifier}.zip.sha1[sha1])`']

== Maven Plugins

[cols="5*",opts="headers"]
|===
//|Sub project
|Module
|Version
|Binary
|tar.gz Source
|zip Source

|===

jsonpathTable2::example$downloads.yml['$.maven_plugins.*', 'title|!!changelog ? `{repo-base}/$\{changelog}[$\{version}]` : version |`{mirror}/$\{artifactId}-$\{version}.jar{query}[jar] ({dist}/$\{artifactId}-$\{version}.jar.asc[asc], {dist}/$\{artifactId}-$\{version}.jar.sha1[sha1])` |!!targz ?  `{mirror}/$\{artifactId}-$\{version}-source-release.tar.gz{query}[tar.gz] ({dist}/$\{artifactId}-$\{version}-source-release.tar.gz.asc[asc], {dist}/$\{artifactId}-$\{version}-source-release.tar.gz.sha1[sha1])` : "" |`{mirror}/$\{artifactId}-$\{version}-source-release.zip{query}[zip] ({dist}/$\{artifactId}-$\{version}-source-release.zip.asc[asc], {dist}/$\{artifactId}-$\{version}-source-release.zip.sha1[sha1])`']

== Historical releases

If you are looking for previous releases of Apache Felix, have a look in the https://archive.apache.org/dist/felix/[archives].