= Apache Felix iPOJO Feature Overview

_This page is an attempt to put all of the features and benefits of iPOJO into a single high-level list so that it is easy to see why you will want to use iPOJO for your applications.
This list is not exhaustive, but represents the set of features that are potentially most likely to be needed or are unique._

== Core Features

* _POJO-based approach_ - Most components can simply be POJOs and need not have iPOJO- or OSGi-specific API in them.
* _Simple service provisioning_ - iPOJO manages all aspects of providing an OSGi service.
* _Service property management_
 ** Can be controlled by configuration properties.
 ** Can be mapped to member fields and automatically updated by the component instance at run time by just changing the member field value.
* Service life cycle participation
 ** The component instance can participate in the service life cycle by declaring a boolean member field that indicates when the service is actually valid (normally a service is assumed to be       valid if the component instance's dependencies are satisfied).
* _Rich service dependency model_ - Automatically manages a full spectrum of      service dependencies.
 ** _Optional/mandatory_ service dependencies.
 ** _Singular/aggregate_ service dependencies.
 ** _Default service implementations_ - The component can provide default       implementations of dependent services if no providers are available.
 ** _Member field or method injection_ - Also supported in combination.
  *** Member field injection does not require cluttering component code with bind/unbind methods.
  *** Member method injection supports various method signatures
   **** method() - Acts as a simple event-callback mechanism.
   **** method(<service-interface>svc) - Receives the service object cast to the appropriate interface.
   **** method(ServiceReference ref) - Receives the OSGi ServiceReference for the service object.
   **** method(ServiceReference ref, <service-interface>svc) - Receives the OSGi ServiceReference and the service object cast to the appropriate interface.
 ** _Binding policies_ -       Allow components to control how/when their dependencies are bound.
  *** _Static_ - Static dependencies _cannot_ change        without invalidating the component instance, so injected services        typically do not change at run time and service departures typically        result in the component instance being destroyed and potentially        recreated.
  *** _Dynamic_ - Dynamic dependencies _can_ change        without invalidating the component instance, so injected services can        change at run time, but _do not_ change with respect to service        priority changes (i.e., they do not automatically switch if a higher        priority service appears).
  *** _Dynamic priority_ - Dynamic priority dependencies _can_ change without invalidating the component instance and _do_ dynamically update based on service priority rankings at run time.
* _Configuration property management_ - Integrated with OSGi Configuration Admin      service.
* _Member field/member method injection_ - Also supported in combination.
 ** _Service property propagation_ - Configuration properties can be configured to       update service properties if the component instance is providing a       service.
* _Sophisticated concurrency handling_ - Externalizes concurrency issues so that      component code does not need to worry about services changing while they      are in use (i.e., no locking protocol in component code).
* _Deferred instance creation_ - POJO instances are not created until they      are actually needed, thus reducing start-up overhead.
* _Introspection support_ -      Supports introspecting a component instance and the state of its      dependencies.
 ** Interactive introspection is supported by an arch command for Felix' shell.
* _Extensible_ - All      iPOJO features are implemented via a set of `handlers`, which is an      extensibility mechanism open to developers by which they can support      custom functionality (e.g., exporting a provided service remotely, etc.).

== Advanced/Experimental Features

* _Composite model_ -      iPOJO supports a flexible architectural-like model for composing services.
 ** _Flexible composites_ - A       composite is an abstract component implementation.
 ** _Sub-services and sub-components_ - Unlike traditional component composition, an        iPOJO composite can be described in terms of services in addition to        sub-components;
thus sub-service implementation selection is deferred        until run time.
 ** _Optional/mandatory_ sub-services and/or sub-components.
 ** _Singular/aggregate_ sub-services and/or sub-components.
 ** _Hierarchical_ - A       composite component may contain other composite components.
 ** _Composite scoping_ - A composite acts as a scoping mechanism        where sub-services/sub-components are not visible externally and        external services are not visible internally.
 ** _Service dependencies_ - A       composite has the full expressive capabilities of primitive components       when it comes to service dependencies (see above description of service       dependencies in core features).
 ** For a composite, a service dependency        effectively imports an external service into the composite scope from        its parent composite (which may be the OSGi service registry in the root        case).
 ** _Composite is just a component_ - Composites can be instantiated and       automatically managed just like a primitive component.
