= Supported Java Virtual Machines

|===
| Features | Sun JVM (1.4, 5, 6) | Oracle JVM and OpenJDK | Harmony | JamVM | Mika | JRockit | Dalvik (Android)

| Core features
| __
| __
| __
| __
| __
| __
| __

| Composites features
| __
| __
| __
| __
| __
| __
| __

| Configuration Admin
| __
| __
| __
| __
| __
| __
| __

| Temporal service dependencies
| __
| __
| __
| __
| __
| __
| __

| Whiteboard and Extender pattern handler
| __
| __
| __
| __
| __
| __
| __

| Event admin handler
| __
| __
| __
| __
| __
| __
| __
|===

Feel free to send a mail on the Felix mailing list if a JVM is not listed here.

'''

INFO: *Note about Android* iPOJO is supported on Android except for two features:

* Nullable are not supported (Default-Implementations are supported)
* Composites cannot provide services (but they can export services)

These two limitations comes from the Android VM (Dalvik) that does not support the definition of new classes at runtime (i.e.
dynamically generated classes).

INFO: *Note about Android* iPOJO 1.6+ uses smart proxy by default.
On Android this is not supported, however, you can disable the proxies with: `proxy="false"` in the service requirements.
