Title: ipojo-support

=== Mailing List

iPOJO is hosted as an Apache Felix sub-project, you can ask questions by sending mails to the Felix mailing lists.
There is two mailing lists:

* The users mailing list
* The developer mailing list

Subscribe to the Felix users mailing list by sending a message to link:mailto:users-subscribe@felix.apache.org[users-subscribe@felix.apache.org];
after subscribing, email questions or feedback to link:mailto:users@felix.apache.org[users@felix.apache.org].

Either, if you want to be involved, subscribe to the Felix dev mailing list by sending a message to link:mailto:dev-subscribe@felix.apache.org[dev-subscribe@felix.apache.org];
after subscribing, email ideas or feedback to link:mailto:dev@felix.apache.org[dev@felix.apache.org].

=== Bug Tracker

If you want a features, an improvement or report a bug, open an issue on the Apache Felix bug tracker:

* Go to the https://issues.apache.org/jira/browse/FELIX page
* Create an account or log in.
* Open the 'Create a new issue in project Felix' form.
* Then, select the Felix project and the issue type (improvement, bug, wish, new feature...)
* At the second step, select the *iPOJO* component and fill out the form (please select the affected version only)
* Finally click on the create button

You can also watch the issue to monitor progress.
The iPOJO team tries to give you quick and frequent feedback on issues.
