= Board Report (2007-09)

*[SUBMITTED]({{ refs.submitted.path }})*

Community

* Added Stuart McCulloch as new committer.
* Added new example application and documentation to the web site.
(http://cwiki.apache.org/FELIX/apache-felix-application-demonstration.html)
* Accepted revised community roles/process document that takes into account our TLP move.
* Upayavira announced his intention to step down from the Felix PMC and the actions necessary to do so have commenced.
* New Felix logo and website layout created.
* Donation of Deployment Admin implementation was announced, expected next month.

Migration to TLP

* Appears to have been completed.

Software

* Released the first `1.0.0` non-incubator release of the Felix framework, including various sub-project releases to support the framework (e.g., Maven plugin for creating bundles, shell-related bundles for interacting with the framework, etc.)
* Uncovered and resolved a couple minor bugs in the `1.0.0` release, so a `1.0.1` release is already in the works.
* Fixed a number of concurrency issues in the Config Admin and Declarative Services implementations reported by the user community.

Licensing and other issues

* None.
