= Board Report (2010-09)

*[SUBMITTED]({{ refs.submitted.path }})*

_Community_

* Added Sanjeeb Sahoo as a committer.

_Software_

* Recent subproject releases: ** Bundle Repository (1.6.4) ** Configuration Admin (1.2.8) ** Event Admin (1.2.4) ** File Install (3.0.2) - Maintenance release for auto-bundle deployer.
** Framework (3.0.1, 3.0.2) - Core OSGi framework maintenance releases.
** Framework Security (1.4.0) - Framework security provider implementation maintenance release.
** iPOJO Arch for Gogo (1.0.0) - Initial release of Gogo shell command for inspecting iPOJO components.
** iPOJO Core, Annotations and Manipulator (1.6.4) - Maintenance release for OSGi-based component framework.
** Main (3.0.1, 3.0.2) - Framework launcher maintenance releases.
** Remote Shell (1.1.0) - Minor feature improvement release to simple telnet service.
** SCR (Declarative Services) (1.6.0)  ** Web Console (3.1.0, 3.1.2)  ** Web Console Memory Usage Plugin (1.0.2)

_Licensing and other issues_

* Karaf subproject promoted to TLP.
* Need to have discussion on how to handle provisional OSGi APIs in our releases.
It is not clear if we should include provisional OSGi API since it is not officially released by the OSGi Alliance and is therefore subject to change and/or not always officially sanctioned (i.e., made publicly available by the OSGi Alliance).
At a minimum, we need to define an approach to informing users if provisional API is included that it is not [yet]({{ refs.yet.path }}) official OSGi API.
