= Board Report (2008-03)

*[SUBMITTED]({{ refs.submitted.path }})*

Community

* Added Stuart McCulloch to the PMC.
* Added Christian van Spaandonk as a committer to work on Deployment Admin.

Software

* Released `1.0.1` version of core Felix sub-projects (i.e., framework and main).
This release fixed mostly minor bugs discovered since the prior release, although there were a few minor new features added as well.
* Released `1.0.3` release of Felix framework/main subprojects;
which included numerous bug fixes and feature ehancements (including support for running the framework on Google's Android).
* Released numerous other subprojects, including Bundle Plugin, SCR Plugin, OBR Plugin, Preferences, Config Admin, Metatype, Event Admin, and Bundle Repository.
* Finalized Deployment Admin contribution from Luminis and committed it to our SVN repository.
* Finalized Peter Kriens' contribution of the File Install bundle and committed it to our SVN repository.
* Karl Pauls committed a significant patch that adds more complete security framework to the Felix framework and also provides implementations for security-related OSGi standard services (e.g., Permission Admin and Conditional Permission Admin);
these improvements will be made available in a future release.

Licensing and other issues

* None this period.
