= Board Report (2009-12)

*[SUBMITTED]({{ refs.submitted.path }})*

_Community_

* Added new committer: Adam Wojtuniak.
* Updated front web page to highlight Felix subprojects.
* Felix/OSGi Track at ApacheCon US was a success.
* Devoxx OSGi at Apache Birds Of A Feather session was well received.
* GlassFish v3 using the Apache Felix framework and a handful of other Felix subprojects goes final December 10th.

_Software_

* Recent contributions: ** OSGi User Admin specification implementation contribution accepted from Adam Wojtuniak.
** OSGi IO Connector specification implementation contributed from Adam Wojtuniak.
* Recent subproject releases: ** File Install (2.0.0, 2.0.4) ** Framework (2.0.1, 2.0.2) ** Gogo (0.2.2) ** HTTP Service (2.0.2, 2.0.4) ** iPOJO Ant Task (1.4.2) ** iPOJO Online Manipulator (1.4.2) ** iPOJO Web Console Plugin (1.4.4) ** Karaf (1.0.0, 1.2.0) ** Main (2.0.1, 2.0.2) ** Maven Bundle Plugin (2.0.1) ** Maven iPOJO Plugin (1.4.2) ** Maven SCR Plugin (1.4.0) ** Preferences (1.0.4) ** SCR (1.2.0) ** Web Console (2.0.0, 2.0.2)

_Licensing and other issues_

* Executed OSGi CT licensing agreement to give Apache committers access to the OSGi CT.
