= Board Report (2007-06)

*[SUBMITTED]({{ refs.submitted.path }})*

Community

* Feathercast Felix podcast released.
* Presentations at OSGi Community Event on June 26/27.
* Added Clement Escoffier as a new committer.
* Added Niclas Hedhman as a new committer/PMC member.
* Continued work on web pages (e.g., new tutorials).
* Proposed slightly revised community roles/process document that takes into account our TLP move and explicitly resolves an issue that came up on the private mailing list regarding the nomination process for committers/PMC members.

Migration to TLP

* Verified committer access to new web site.
* Deleted incubator web site content.
* Removed incubator disclaimers from SVN and updated SVN artifacts to no longer mention the incubator or the old incubator web site or mailing lists;
the only remaining incubator references are in our version numbers, which will be removed when we make our first non-incubator release.
* Still some minor incubator status page clean up remaining.

Software

* Some good commits in the area of specification compliance (one in the area of require-bundle functionality and another fix for a long standing issue for dynamic package imports) and in the area of performance (by adding package indexing to the framework resolver).
* Added experimental features to Felix to flesh out some potential ideas for next OSGi specification;
these features are trying to deal with scenarios such as byte code injection in modules.
* Other various smallish improvement and minor bug fix commits.

Licensing and other issues

* None.
