= Board Report (2009-06)

*[SUBMITTED]({{ refs.submitted.path }})*

Community

* Added two new PMC members: Clement Escoffier and Guillaume Nodet.
* Added five new committers: Chris Custine, Hiram Chirino, Freeman Yue Fang, James Strachan, and Gert Vanthienen.
* Contribution from Paremus of Sigil OSGi tooling project;
this has been voted on and is undergoing the IP clearance process.
* OSGi tutorial using Felix Framework given at EclipseCon in late March.
* Apache Felix presentation and BOF at ApacheCon EU 2009.

Software

* Released the following subprojects: ** Bundle Repository (1.4.0) - Some improvements to align with the OSGi RFC, but mostly minor.
** Dependency Manager (2.0.1) ** Dependency Manager Shell (2.0.1) ** Framework (1.6.0, 1.6.1, 1.8.0) - The latest release adds more complete support for fragment bundles, bringing Felix ever closer to specification compliance.
** Log Service (1.0.0) - Initial release of a very simple OSGi Log Service implementation.
** Main (1.6.0, 1.6.1, 1.8.0) - This subproject is released in lockstep with the framework subproject.
** Maven SCR Plugin (1.0.10, 1.2.0) ** junit4osgi (1.0.0) ** File Install (0.9.2, 1.0.0) - Continued improvements and bug fixes.
** SCR (1.0.8) ** Jetty HTTP Service (1.0.0) - Initial release of Jetty-based implementation of the OSGi HTTP Service.
** Shell (1.2.0) - Added some new commands for inspecting framework state and other minor improvements.
** Shell TUI (1.2.0) - Minor bug fix release.
** UPnP Extra (0.4.0) ** UPnP Tester (0.4.0) ** Web Console (1.2.8, 1.2.10)
* Incorporated the Apache ServiceMix Kernel contribution, renamed to Apache Felix Karaf, into the Felix project.
* Peter Kriens' OSGi shell contribution has finished IP clearance and is awaiting inclusion into SVN repo.

Licensing and other issues

* None.
