= Board Report (2008-12)

*[SUBMITTED]({{ refs.submitted.path }})*

Community

* Presented Felix at ApacheCon US.
* Contributions from the CXF community for patches to Felix to support distributed OSGi features from the next OSGi specification release.
* Sun released GlassFish v3 Prelude, which includes Felix.

Software

* Still working on incorporating the new Log Service contribution from PAX;
largely delayed due to a naming issue and lack of time.
* Released version 1.2.1 of Felix (includes Framework 1.2.1, Main 1.2.1) to address a performance regression.
* Released version 1.2.2 of Felix (includes Framework 1.2.2, Main 1.2.2) to address a security bug.
* Released version 1.4.0 of Felix (includes Framework 1.4.0, Main 1.4.0, Bundle Repository 1.2.1);
this was a fairly major release including support for features from the coming OSGi R4.2 specification and many more resolved compliance issues and small bugs.
* Released various other subprojects (e.g., iPOJO 1.0.0, Web Console 1.2.0, Remote Shell 1.0.2, SCR 1.0.6, Maven SCR Plugin 1.0.8, Maven Bundle Plugin 1.4.3).
* Released subproject bundles are now available via an OBR repository for easy deployment into Felix (and other OSGi frameworks).
* Various fixes and enhancements to HTTP Service subproject, including improved alias resolution, better cache support with inclusion of Last Modified timestamps, and publishing actual ports used as service properties.

Licensing and other issues

* Need to investigate licensing issue for a JMX admin console contribution.
