:doctype: book

Title: Describing components

= Describing your iPOJO components

_This section describes the different features supported by iPOJO.
This page aims to answer to the following question: "What can I write in my iPOJO component descriptor?"_

== Core features

Core features are provided with the iPOJO runtime bundles.
You can use it directly, as soon as the iPOJO runtime is deployed.

* link:{{ refs.service-requirement-handler.path }}[How to require a service]
* link:{{ refs.providing-osgi-services.path }}[How to publish and provide a service]
* link:{{ refs.lifecycle-callback-handler.path }}[How to react to lifecycle state changes]
* link:{{ refs.configuration-handler.path }}[How to description component configuration]
* link:{{ refs.architecture-handler.path }}[How to enable/disable instance introspection]
* link:{{ refs.controller-lifecycle-handler.path }}[How to act on the instance state from the implementation]

== Extensions

Extensions _extend_ the iPOJO model to add a specific functionality.
This is made thanks to the external handler mechanism.
So before using one of these features, deploy the attached external handler.

* link:{{ refs.event-admin-handlers.path }}[How to receive and send events with the Event Admin]
* link:{{ refs.ipojo-jmx-handler.path }}[How to reconfigure instances with JMX]
* link:{{ refs.extender-pattern-handler.path }}[How to implement an extender pattern]
* link:{{ refs.white-board-pattern-handler.path }}[How to implement a whiteboard pattern]
* link:{{ refs.temporal-service-dependency.path }}[How to wait for services and inject proxies]

== A missing functionality ?

iPOJO component model is extensible.
So, you can implement your own handler managing you specific requirement.
Refer the handler development guide (link:{{ refs.how-to-write-your-own-handler.path }}[How to write your own handler]) for more details.
