= Using XML Schemas

_iPOJO provides XML schemas to check iPOJO descriptors (i.e.
metadata.xml).
Several schemas are provided in order to describe the core syntax, compositions and external handlers._+++<table class="table">++++++<tbody>++++++<tr>++++++<th>+++Schema+++</th>+++
        +++<th>+++URL+++</th>++++++</tr>+++
    +++<tr>++++++<td>+++iPOJO Core+++</td>+++
        +++<td>++++++<a href="http://felix.apache.org/ipojo/schemas/CURRENT/core.xsd" class="external-link" rel="nofollow">+++http://felix.apache.org/ipojo/schemas/CURRENT/core.xsd+++</a>++++++</td>++++++</tr>+++
    +++<tr>++++++<td>+++iPOJO Composite+++</td>+++
        +++<td>++++++<a href="http://felix.apache.org/ipojo/schemas/CURRENT/composite.xsd" class="external-link" rel="nofollow">+++http://felix.apache.org/ipojo/schemas/CURRENT/composite.xsd+++</a>++++++</td>++++++</tr>+++
    +++<tr>++++++<td>+++Temporal Dependency Handler+++</td>+++
        +++<td>++++++<a href="http://felix.apache.org/ipojo/schemas/CURRENT/temporal.xsd" class="external-link" rel="nofollow">+++http://felix.apache.org/ipojo/schemas/CURRENT/temporal.xsd+++</a>++++++</td>++++++</tr>+++
    +++<tr>++++++<td>+++Whiteboard pattern handler+++</td>+++
        +++<td>++++++<a href="http://felix.apache.org/ipojo/schemas/CURRENT/whiteboard-pattern.xsd" class="external-link" rel="nofollow">+++http://felix.apache.org/ipojo/schemas/CURRENT/whiteboard-pattern.xsd+++</a>++++++</td>++++++</tr>+++
    +++<tr>++++++<td>+++Extender pattern handler+++</td>+++
        +++<td>++++++<a href="http://felix.apache.org/ipojo/schemas/CURRENT/extender-pattern.xsd" class="external-link" rel="nofollow">+++http://felix.apache.org/ipojo/schemas/CURRENT/extender-pattern.xsd+++</a>++++++</td>++++++</tr>+++
    +++<tr>++++++<td>+++Event Admin handlers+++</td>+++
        +++<td>++++++<a href="http://felix.apache.org/ipojo/schemas/CURRENT/event-admin.xsd" class="external-link" rel="nofollow">+++http://felix.apache.org/ipojo/schemas/CURRENT/event-admin.xsd+++</a>++++++</td>++++++</tr>+++
    +++<tr>++++++<td>+++JMX handler+++</td>+++
        +++<td>++++++<a href="http://felix.apache.org/ipojo/schemas/CURRENT/jmx.xsd" class="external-link" rel="nofollow">+++http://felix.apache.org/ipojo/schemas/CURRENT/jmx.xsd+++</a>++++++</td>++++++</tr>++++++</tbody>++++++</table>+++

NOTE: the schemas are also provided inside the iPOJO bundles.

NOTE: to use the 'dev' schemas, replace `CURRENT` by `SNAPSHOT` in the URL.
To use those schemas you have to declares those schemas in your metadata.xml file such as in the next snippet using the iPOJO core XML-schema:

 :::xml
 <ipojo
     xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
     xsi:schemaLocation="org.apache.felix.ipojo http://felix.apache.org/ipojo/schemas/CURRENT/core.xsd"
     xmlns="org.apache.felix.ipojo">
     <component classname="..." ....>
     </component>
 </ipojo>

First, declare the 'XMLSChema-instance' namespace.
Then, declares used namespaces and schemas in the 'xsi:schemaLocation' attribute.
This attribute contains pairs 'namespace url' separated by spaces.
Finally, declares the default namespace to "org.apache.felix.ipojo".
You can also use several schemas in the same descriptor by using a header like:

 :::xml
 <ipojo xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
 	xsi:schemaLocation="org.apache.felix.ipojo http://felix.apache.org/ipojo/schemas/CURRENT/core.xsd
 	    org.apache.felix.ipojo.extender http://felix.apache.org/ipojo/schemas/CURRENT/extender-pattern.xsd"
 	xmlns="org.apache.felix.ipojo"
 	xmlns:extender="org.apache.felix.ipojo.extender">
 	<component
 		classname="org.apache.felix.ipojo.junit4osgi.impl.JunitExtender">
 		<extender:extender extension="Test-Suite"
 			onArrival="onBundleArrival" onDeparture="onBundleDeparture" />
 		<callback transition="invalidate" method="stopping" />
 		<callback transition="validate" method="starting" />
 		<provides />
 	</component>
 	<instance
 		component="org.apache.felix.ipojo.junit4osgi.impl.JunitExtender" />
 </ipojo>

The only difference is contained in the 'schemaLocation' attribute, which contains several pairs.
You also need to declare the namespace of the used external handler.

If you declare schemas, the iPOJO manipulator automatically checks the validity of the descriptor against the declared schemas.
Moreover, if you use 'advanced' XML Editor supporting schemas, editing iPOJO descriptors should be eased with auto-completion features.

== Avoid downloading XML Schemas during the build process

The manipulator embeds the iPOJO XML Schemas to avoid using a network connection to download them during the validation process.
Keep the same url, the manipulator will just resolve the URL differently to use embedded schemas.
You can also skipped this shortcut thanks the the `ignoreEmbeddedSchemas` parameter (refer to the xref:documentation/subprojects/apache-felix-ipojo/apache-felix-ipojo-tools/ipojo-ant-task.adoc[Ant Task]) and to the xref:documentation/subprojects/apache-felix-ipojo/apache-felix-ipojo-tools/ipojo-maven-plug-in.adoc[Maven Plugin] for further information about configuration).
