= Apache Felix Preferences Service

The OSGi service compendium specification defines a general purpose service to store data persistently, so that they can survive the restart of a bundle or of the whole OSGi container.
This service is not intended to be a full-featured persistence layer for OSGi bundles, rather a simple tool to store informations that can be used in various stages of the bundle lifecycle.

The service supports the storage of scalar values (boolan, double, float, int, long and strings) and byte arrays, arranged in a hierarchical model.
While there is no limitations on the size of data objects stored, the specification clearly states that the Preferences Service is intended to store only small objects.

The entry point to the Preferences Service API is the _PreferencesService_ interface.
It provides access to different roots of Preferences trees:

* a _system root_
* any number of _user roots_ The _user root_ for a specific user is automatically created the first time it is requested.

User roots and system root are bundle specific, and cannot be accessed by other bundles.

== Accessing the Preferences Service

If the OSGi platform provides a Preferences Service, getting a reference to it is as simple as doing a normal OSGi service lookup:

----
public class Activator implements BundleActivator
{
	public void start(BundleContext context) throws Exception
	{
		ServiceReference ref = context.getServiceReference(PreferencesService.class.getName());
		if (ref != null)
		{
			PreferencesService service = (PreferencesService) context.getService(ref);

			//...
		}
	}

	//..
----

To access the _system root_

 		Preferences systemRoot = service.getSystemPreferences();

To access a _user root_

 		Preferences mickeyRoot = service.getUserPreferences("mickey");

== Store and retrieve value in Preferences

The _Preferences_ interface offers some simple methods to store key/value pairs:

----
public void put(String key, String value);

public void putInt(String key, int value);

public void putLong(String key, long value);

public void putBoolean(String key, boolean value);

public void putFloat(String key, float value);

public void putDouble(String key, double value);

public void putByteArray(String key, byte[] value);
----

For each of these methods, a correspondent _get_ method exists.
Get methods always accept two arguments: the first to specify the key of the property to retrieve, the second a default value in case of not-existent property (or in case of errors).
For instance:

 public float getFloat(String key, float def)

As mentioned before, data can be stored in a hierarchical way.
The following example shows how to create nodes under the system root to store data:

 Preferences colorPreferences = service.getSystemPreferences().node("color");
 colorPreferences.setString("background", "#eeeeee");
 colorPreferences.setString("font", "#000000");

The Preferences interface offers different method to navigate the preference tree, like `childrenNames(), parent() and node(String name)`.
Check the http://www.osgi.org/javadoc/r4v41/org/osgi/service/prefs/Preferences.html[Preferences interface Javadoc] for a complete list.

== flush() and sync()

Two additional methods of the _Preferences_ interface can be useful.

* _flush()_ forces any change of the Preferences object to be saved in the persistent storage
* _sync()_ reload the content of the Preferences object from the persistent storage;
before reloading, all the contents are saved
