= Apache Felix Project Info

There are different roles with which Felix community members may be associated, these roles are: users, contributors, committers, and Project Management Committee (PMC) members.
These roles are assigned and assumed based on merit.
Everyone in the Felix community can participate to whatever level they desire, but participating and the resulting merit gained is directly linked to the role an individual may obtain.
To further understand how the Felix community operates, refer to the https://www.apache.org/foundation/how-it-works.html[Community Roles and Processes] document and/or join the <<_mailing_lists,mailing lists>>.

== Committers and Project Management Committee (PMC)

See Apache Phone Book: https://people.apache.org/phonebook.html?pmc=felix[Apache Felix Committers and PMC members]

=== Past members:

* Niclas Hedhman (stepped down 1/26/2009)
* Trustin Lee (stepped down 2/9/2008)
* Upayavira (stepped down 9/11/2007)

== Source Code

This project uses https://git-scm.com/[git] to manage its source code.
Instructions on git can be found at https://git-scm.com/docs[git docs].

=== Web Access

The following is a link to the online source repository.

https://github.com/apache/felix-dev

=== Committer and anonymous access

The Felix source code can be checked out (anonymously) with the following command:

[source,sh]
 $ git clone https://github.com/apache/felix-dev

== Mailing lists

The following mailing lists have been established for Apache Felix.
For each list, there is a subscribe, unsubscribe, and archive link.

|===
| Name | Subscribe | Unsubscribe | Archive

| _Felix Users_ - For people using Felix subprojects and/or developing bundles.
| link:mailto:users-subscribe@felix.apache.org[Subscribe]
| link:mailto:users-unsubscribe@felix.apache.org[Unsubscribe]
| https://www.mail-archive.com/users%40felix.apache.org/[www.mail-archive.com]

| _Felix Dev_ - For people interested in the internal development of Felix subprojects.
| link:mailto:dev-subscribe@felix.apache.org[Subscribe]
| link:mailto:dev-unsubscribe@felix.apache.org[Unsubscribe]
| https://www.mail-archive.com/dev%40felix.apache.org/[www.mail-archive.com]

| _Felix Commits_ - For people intested in Felix subproject code changes.
| link:mailto:commits-subscribe@felix.apache.org[Subscribe]
| link:mailto:commits-unsubscribe@felix.apache.org[Unsubscribe]
| https://www.mail-archive.com/commits%40felix.apache.org/[www.mail-archive.com]
|===

== Issue Tracking

This project uses https://www.atlassian.com/software/jira[JIRA], a J2EE-based, issue tracking and project management application.
We use it for bugs, tasks and code contributions.

Before creating a new issue, please make sure nobody has already added the issue you're reporting.
When you do add an issue, please try to make it as informative as possible.

The issue tracker can be found at https://issues.apache.org/jira/browse/FELIX
