= Dependency Manager - Bundles and Dependencies

The dependency manager project consists of the following bundles.
For each bundle, we also list its dependencies in the form of package imports, plus a suggestion on a bundle that resolves them.

* `org.apache.felix.dependencymanager` - 4.0.0 - This is the core bundle, containing the code for working with the Java based API.
 ** org.osgi.framework;version="[1.5,2)" - provided by the OSGi framework itself
 ** org.osgi.util.tracker;version="[1.4,2)" - provided by the OSGi framework itself
 ** org.osgi.service.cm;version="[1.3,2)" - provided by Apache Felix Configuration Admin, or the OSGi Compendium bundle
 ** org.osgi.service.metatype;version="[1.1,2)" - provided by Apache Felix Metatype, or the OSGi Compendium bundle
* `org.apache.felix.dependencymanager.runtime` - 4.0.0 - This is the runtime bundle that you need, together with the core bundle above, if you want to work with annotations.
 ** org.osgi.framework;version="[1.5,2)" - provided by the OSGi framework itself
 ** org.osgi.service.packageadmin;version="[1.2,2)" - provided by the OSGi framework itself
 ** org.apache.felix.dm;version="[4,5)" - provided by the core bundle
 ** org.apache.felix.dm.context;version="[4,5)" - provided by the core bundle
 ** org.osgi.service.log;version="[1.3,2)" - provided by Apache Felix Log Service, or the OSGi Compendium bundle
* `org.apache.felix.dependencymanager.shell` - 4.0.0 - This is the shell bundle.
It only contains the shell commands, so you need it if you want to use those.
 ** org.apache.felix.dm;version="[4.0,5)" - provided by the core bundle
 ** org.apache.felix.service.command;version="[0.10,1)";status=provisional
 ** org.osgi.framework;version="[1.5,2)" - provided by the OSGi framework itself
* `org.apache.felix.dependencymanager.annotation` - 4.0.0 - This is not a bundle, but code you need when compiling your bundles that contain annotations.
Notice that the annotation jar contains OSGi headers in its manifest, but this bundle is not meant to be included in the OSGi framework runtime (the OSGi headers are only present in order to allow you to drag and drop the dependency manager annotation bundle in your buildpath project).
