=  Apache Felix UPnP

== Introduction

The Felix UPnP project provides an implementation of the OSGi UPnP specification (version 1.1) as described in the http://www.osgi.org/Specifications/HomePage[OSGi Service Compendium (Release 4)] . The specification is implemented by the _org.apache.felix.upnp.basedriver_ bundle and it comes with other bundles, which have been developed to ease the writing and testing of UPnP code.

The OSGi UPnP specification defines a set of interfaces which should be used by the developers in order to write UPnP Devices and UPnP Control Points on the OSGi Service Platform.
From the OSGi point of view, UPnP devices are services registered with the framework, thus the different phases of the UPnP protocol stack, as defined in the http://www.upnp.org/resources/documents/CleanUPnPDA101-20031202s.pdf[UPnP™ Device Architecture (UDA 1.0)], have been mapped to the discovery and notification mechanisms offered by the OSGi framework.

The specification defines a UPnP Base Driver component that acts as software bridge between UPnP networks and OSGi.
Developers writing UPnP code do not need to interact directly with the driver through some API.
The driver works in background by exporting the registered services as UPnP devices, and by registering as services the UPnP devices discovered on UPnP networks.
However, the Felix UPnP project has defined few additional interfaces, so a base knowledge of the way the UPnP Base Driver works is useful and will help developers to write their code.

Table of Content:

. xref:documentation/subprojects/apache-felix-upnp/upnp-getting-started.adoc[Getting Started]
. xref:documentation/subprojects/apache-felix-upnp/upnp-driver-architecture.adoc[Overview of the Base Driver Architecture]
. xref:documentation/subprojects/apache-felix-upnp/upnp-testing-devices.adoc[Testing UPnP devices]
. xref:documentation/subprojects/apache-felix-upnp/upnp-testing-devices/upnp-examples.adoc[The UPnP examples]
. xref:documentation/subprojects/apache-felix-upnp/upnp-testing-devices/upnp-examples/upnp-writing-cd-and-cp.adoc[Writing UPnP Devices and Control Points]
. xref:documentation/subprojects/apache-felix-upnp/upnp-known-issues.adoc[Known issues]
. xref:documentation/subprojects/apache-felix-upnp/upnp-acknowledgments.adoc[Acknowledgments]
