= Apache Felix Maven OSGi Plugin

WARNING:: totally obsolete.
WARNING:: most of the mdtext content was not converted.
Consult git history

The OSGi plugin for Maven 2.0 is currently under development at the http://incubator.apache.org/felix[Apache Felix] project, and this page documents the plugin's current state of functionality and will serve as a how-to guide for its use.

The main task this plugin aims to accomplish is the generation of OSGi-compliant bundle archives.
To this end, the plugin provides an integraton with Maven 2's project object model (POM) with particular focus on manipulation of the bundle's manifest and the automated generation of some headers (e.g., Bundle-ClassPath, Import-Package, and Bundle-Activator).

== Current Plugin Functionality

=== Standard Features

The plugin provides the user with two ways to manipulate the contents of a bundle's manifest:

. Path and filename of a manifest.mf file in which the contents will be merged with the default entries generated by Maven 2.
Note that _any_ manifest entry can be added to the bundle's manifest using this technique - java-standard, osgi-standard, or custom entries.
The path name is relative to the root of the Maven 2 project, and is specified using the following POM notation:


