= Apache Felix Health Checks

Based on a simple HealthCheck SPI interface, Felix Health Checks are used to check the health/availability of Felix systems at runtime based on inputs like

* OSGi framework status
* JMX MBean attribute values
* OSGi service(s) / SCR component(s) availability
* ...
or any context information retrievable via any API

Health checks are easily extensible either by

* configuring the default HealthCheck services in bundle `generalchecks` (can be configuration or scripts)
* or by implementing your own `HealthCheck` to cater special requirements (this is done by just registering a service for this interface)

For simple setups, the out of the box health checks are usually sufficient.

To execute health checks, the Gogo commands `hc:list` and `hc:exec` are provided or with the web console plugin installed, use the URL `/system/console/healthcheck`.

For *detailed documentation*, see https://github.com/apache/felix-dev/blob/master/healthcheck/README.md[README.md] file in source repository.
