= CAT-Scan Project Proposal

All too often one hears anecdotal information about how many bundles get loaded and when.
There have been claims that there is a need to handle tens of thousands of bundles at one time.
Apache Geronimo, a JEE server, fully trussed up, does not load that many jars.
Attendees at the 2008 OSGi conference didn't even know or were hesitant to divulge their bundle usage.

CAT-Scan is a way for developers to collect information on the traits of an application or set of applications deployed on an OSGi framework.
This information can be used by developers, framework implementors, and researchers to obtain a clearer, more accurate, picture of their OSGi usage rather than the anecdotal information one gets from, say, conferences.

Information that is collected in the form of run-logs can be used by the developer to appropriately configure their OSGi frameworks.
Run-logs can be sent to OSGi vendors to assist them in support and help make framework design decisions.
Characteristics of applications collected from this tool can be used by researchers to provide concrete data as to the traits of real world applications.
This data can be made anonymous to protect installations' trade secrets while still providing great value.

== Table of Contents

{% for label, page in children %}* link:{{ page.path }}[{{ page.headers.title }}] {% endfor %}
